### PR TITLE
restricted dump to list of users

### LINKED ISSUE #1: dump publishes private rooms
Hi,

via ```rss dump``` it is possible to get names of private rooms in RocketChat, which is to my mind a kind of security risk as private room names are hidden to others.

Ciao
Marcus

### PR DESCRIPTION
**Pull request by localguru**
Hi Robert,

an first idea how one could restrict the dump command to a list of users and keep it hidden; fixes #1

Ciao
Marcus

### CODE REVIEW

**Comment by choltkamp** [comment]
I support this.

**Comment by Flipez** [comment]
Thank you @localguru 

I've released 1.2.0 with your fix. Please let me know if something does not work as intended :)

**Comment by localguru** [comment]
Perfect, thanks Robert!

**Comment by localguru** [comment]
Ah, one thing I just noticed. I would put the `feeds = checker.getAllFeeds()` line after `if msg.message.user.name ...`. It does not make sense to search and afterwards forbidden or not:

```
  robot.respond /rss dump$/i, (msg) ->
    if msg.message.user.name in process.env.HUBOT_RSS_DUMP_USERS.split ","
      feeds = checker.getAllFeeds()
      msg.send JSON.stringify feeds, null, 2
    else
      msg.send "not allowed"
```
Cheers
Marcus

**Pull request merged**
